name: Google Cloud Run Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:

    name: Google Cloud Run Deploy for Speech Demo
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_IMAGE_NAME: kineticsquid/${{ secrets.GCP_APPLICATION }}

    steps:

      - uses: actions/checkout@v2

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Gcloud Docker
        run: gcloud auth configure-docker --quiet

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build hub.docker.com Docker image
        run: docker build ./ -t $DOCKER_HUB_IMAGE_NAME

      - name: Push hub.docker.com Docker image
        run: docker push $DOCKER_HUB_IMAGE_NAME

      - name: Google Cloud Deploy Speech Demo by Action
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ secrets.GCP_APPLICATION }}
          project_id: ${{ secrets.GCP_PROJECT }}
          source: ./
          region: us-central1
          env_vars: |
            STT_API_KEY=${{ secrets.STT_API_KEY }},
            TTS_API_KEY=${{ secrets.TTS_API_KEY }},
            STT_API_URL=${{ secrets.STT_API_URL }},
            TTS_API_URL=${{ secrets.TTS_API_URL }},
            STT_WS_URL=${{ secrets.STT_WS_URL }},
            STT_HOST=${{ secrets.STT_HOST }},
            STT_PORT=${{ secrets.STT_PORT }}


      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"/build